version: "3.7"
services:
  master:
    image: postgres:9.6
    ports:
      - "56430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.2
    volumes:
      - ./volumes/master/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/slave1:/var/lib/postgresql/slave1
      - ./volumes/slave2:/var/lib/postgresql/slave2
  slave1:
    image: postgres:9.6
    ports:
      - "56431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.3
    volumes:
      - ./volumes/slave1/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/slave2:/var/lib/postgresql/slave2
      - ./volumes/master:/var/lib/postgresql/master
  slave2:
    image: postgres:9.6
    ports:
      - "56432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.4
    volumes:
      - ./volumes/slave2/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/master:/var/lib/postgresql/master
      - ./volumes/slave1:/var/lib/postgresql/slave1
volumes:
  pg_data_master:
    driver_opts:
      type: local
      device: ./volumes/master/data
  pg_data_slave1:
    driver_opts:
      type: local
      device: ./volumes/slave1/data
  pg_data_slave2:
    driver_opts:
      type: local
      device: ./volumes/slave2/data
  shared:
    driver_opts:
      type: local
      device: ./volumes/shared
networks:
  pg-practice:
    name: pg-practice-bridge
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.0.0/24
