version: "3.7"
services:
  alpha:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "56430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.2
    volumes:
      - ./volumes/alpha/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/bravo:/var/lib/postgresql/bravo
      - ./volumes/charlie:/var/lib/postgresql/charlie
  bravo:
    image: "postgres:${POSTGRES_VERSION:-11}"
    ports:
      - "56431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.3
    volumes:
      - ./volumes/bravo/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/charlie:/var/lib/postgresql/charlie
      - ./volumes/alpha:/var/lib/postgresql/alpha
  charlie:
    image: "postgres:${POSTGRES_VERSION:-11}"
    ports:
      - "56432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgreS
    networks:
      pg-practice:
        ipv4_address: 172.16.0.4
    volumes:
      - ./volumes/charlie/data:/var/lib/postgresql/data
      - ./volumes/shared:/var/lib/postgresql/shared
      - ./volumes/alpha:/var/lib/postgresql/alpha
      - ./volumes/bravo:/var/lib/postgresql/bravo
volumes:
  pg_data_alpha:
    driver_opts:
      type: local
      device: ./volumes/alpha/data
  pg_data_bravo:
    driver_opts:
      type: local
      device: ./volumes/bravo/data
  pg_data_charlie:
    driver_opts:
      type: local
      device: ./volumes/charlie/data
  shared:
    driver_opts:
      type: local
      device: ./volumes/shared
networks:
  pg-practice:
    name: pg-practice-bridge
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.0.0/24
