name: Test
on: push
jobs:
  test-async-replication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Asyc Replication
      run: sudo make test_async_replication
